import { test, expect } from "../fixtures";
import { getManifest, getActiveRunCount, type Manifest } from "../fixtures/test-data";

/**
 * Comprehensive E2E tests for the Observer Dashboard page (/).
 *
 * These tests run against fixture data generated by generate-fixtures.ts.
 * The fixture manifest provides deterministic counts for assertions.
 */

let manifest: Manifest;

test.beforeAll(async () => {
  manifest = await getManifest();
});

/**
 * Grid-visible run total. Since the kanban wave-3 fixtures, the manifest's
 * runCount counts every run SURFACED on the dashboard (grid-visible runs PLUS
 * the registry-hidden project's needs-you run on the alarm surface — the board
 * columns sum to exactly that number). The KPI tiles and the "All" pill are
 * grid-level metrics (QA F4: hiding removes a project from the GRID), so they
 * count only the runs of the projects in projectCounts.
 */
function gridRunCount(): number {
  return Object.values(manifest.projectCounts).reduce((sum, n) => sum + n, 0);
}

// ---------------------------------------------------------------------------
// Dashboard Loading & Header
// ---------------------------------------------------------------------------

test.describe("Dashboard Loading", () => {
  test("loads the dashboard and displays the header", async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await expect(dashboardPage.heading).toBeVisible({ timeout: 30_000 });
    await expect(dashboardPage.header).toBeVisible();
  });

  test("displays the SSE connection status indicator", async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await expect(dashboardPage.heading).toBeVisible({ timeout: 30_000 });
    await expect(dashboardPage.connectionDot).toBeVisible();
  });

  test("shows settings button in the top bar", async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await expect(dashboardPage.heading).toBeVisible({ timeout: 30_000 });
    await expect(dashboardPage.settingsButton).toBeVisible();
  });

  test("loading skeletons disappear once data loads", async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Skeletons should no longer be visible
    const skeletons = dashboardPage.loadingSkeletons;
    // The main content skeletons (3 placeholders) should be gone
    await expect(dashboardPage.projectGrid).toBeVisible({ timeout: 30_000 });
  });
});

// ---------------------------------------------------------------------------
// KPI Metric Tiles
// ---------------------------------------------------------------------------

test.describe("KPI Metric Tiles", () => {
  test.beforeEach(async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();
  });

  test("displays KPI metric tiles (4 base, or 5 with Stale)", async ({ dashboardPage }) => {
    await expect(dashboardPage.kpiGrid).toBeVisible();
    const tiles = dashboardPage.getKPITiles();
    const count = await tiles.count();
    // 4 base tiles (Total Runs, Active, Completed, Failed) + optional Stale tile
    expect(count).toBeGreaterThanOrEqual(4);
    expect(count).toBeLessThanOrEqual(5);
  });

  test("Total Runs tile shows the correct count", async ({ dashboardPage }) => {
    const tile = dashboardPage.getMetricTile("total-runs");
    await expect(tile).toBeVisible();
    await expect(tile).toContainText("Total Runs");
    await expect(tile).toContainText(String(gridRunCount()));
  });

  test("Active tile shows the active run count", async ({ dashboardPage }) => {
    const tile = dashboardPage.getMetricTile("active");
    await expect(tile).toBeVisible();
    await expect(tile).toContainText("In Progress");
    // §15.1 (owner gate 2026-07-06b, scheduled-state): Active = waiting + pending
    // MINUS sleeping "scheduled" runs. A forever-run parked at an unresolved
    // sleep effect is idle-healthy, not in-progress, so the tile (single
    // counting source) excludes it — getActiveRunCount reconciles this test with
    // that definition instead of the stale raw waiting+pending sum.
    const activeCount = await getActiveRunCount();
    await expect(tile).toContainText(String(activeCount));
  });

  test("Completed tile shows the completed run count", async ({ dashboardPage }) => {
    const tile = dashboardPage.getMetricTile("completed");
    await expect(tile).toBeVisible();
    await expect(tile).toContainText("Completed");
    await expect(tile).toContainText(String(manifest.statusCounts.completed || 0));
  });

  test("Failed tile shows the failed run count", async ({ dashboardPage }) => {
    const tile = dashboardPage.getMetricTile("failed");
    await expect(tile).toBeVisible();
    await expect(tile).toContainText("Failed");
    await expect(tile).toContainText(String(manifest.statusCounts.failed || 0));
  });

  test("KPI tile values sum correctly", async ({ dashboardPage }) => {
    // Total-runs tile === grid run count, with scheduled runs present (§15.1
    // AC-77: the Scheduled column participates in the board total, so the total
    // tile still reconciles to the full grid count).
    //
    // The KPI tiles read the wave-1 single counting source (useAllRuns /
    // /api/runs), which resolves INDEPENDENTLY of waitForData() (that awaits the
    // project grid, fed by the digest). So the tile shows 0 until the async
    // metric settles — poll the parsed value instead of racing a one-shot
    // innerText read.
    const totalTile = dashboardPage.getMetricTile("total-runs");
    await expect
      .poll(async () => {
        const digits = (await totalTile.innerText()).match(/\d+/)?.[0];
        return digits ? parseInt(digits, 10) : null;
      })
      .toBe(gridRunCount());
  });
});

// ---------------------------------------------------------------------------
// Project Health Cards
// ---------------------------------------------------------------------------

test.describe("Project Health Cards", () => {
  test.beforeEach(async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();
  });

  test("renders all project cards from fixtures", async ({ dashboardPage }) => {
    const projectNames = Object.keys(manifest.projectCounts);
    const cards = dashboardPage.getProjectCards();
    await expect(cards).toHaveCount(projectNames.length);
  });

  test("project count label shows the correct number", async ({ dashboardPage }) => {
    const projectNames = Object.keys(manifest.projectCounts);
    await expect(dashboardPage.projectCount).toContainText(
      `${projectNames.length} project`
    );
  });

  test("each project card displays the project name", async ({ dashboardPage }) => {
    const projectNames = Object.keys(manifest.projectCounts);
    for (const name of projectNames) {
      const card = dashboardPage.getProjectCard(name);
      await expect(card).toBeVisible();
      await expect(card).toContainText(name);
    }
  });

  test("project cards show health status label", async ({ dashboardPage }) => {
    // Every project card should show one of: Healthy, Active, Failing
    const cards = dashboardPage.getProjectCards();
    const count = await cards.count();
    for (let i = 0; i < count; i++) {
      const card = cards.nth(i);
      const text = await card.innerText();
      const hasHealthLabel =
        text.includes("Healthy") ||
        text.includes("Active") ||
        text.includes("Failing");
      expect(hasHealthLabel).toBe(true);
    }
  });

  test("project cards display total run count", async ({ dashboardPage }) => {
    // Each project card should contain a number representing total runs.
    // Use Playwright's auto-retrying toContainText instead of a one-shot
    // innerText() read, which can flake when cards are still hydrating.
    const cards = dashboardPage.getProjectCards();
    // Auto-retrying visibility wait before the one-shot count() — the count
    // can otherwise race the grid hydrating and read 0 (same flake class the
    // comment above describes for innerText()).
    await expect(cards.first()).toBeVisible({ timeout: 15_000 });
    const count = await cards.count();
    expect(count).toBeGreaterThan(0);

    for (let i = 0; i < count; i++) {
      await expect(cards.nth(i)).toContainText(/\d+/, { timeout: 10_000 });
    }
  });

  test("project cards show progress bar when tasks exist", async ({ dashboardPage }) => {
    // At least one project card should have a progress bar (tasks text).
    // Same intent as before, but auto-retrying: the previous one-shot
    // count()+innerText() loop raced grid hydration and read 0 cards (the
    // trace showed the locator query resolving before any card mounted while
    // the failure screenshot, ms later, had fully hydrated "N/M tasks" rows).
    // Same flake class — and same cure — as "display total run count" above.
    const cards = dashboardPage.getProjectCards();
    const cardWithProgress = cards.filter({ hasText: "tasks" }).first();
    await expect(cardWithProgress).toBeVisible({ timeout: 15_000 });
  });

  test("expanding a project card reveals run cards", async ({ dashboardPage, page }) => {
    // Click the first project card to expand it
    const firstCard = dashboardPage.getProjectCards().first();
    await firstCard.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    // Wait for run cards to appear inside the expanded card
    const runCards = dashboardPage.getRunCards();
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });
  });
});

// ---------------------------------------------------------------------------
// Filter Pills
// ---------------------------------------------------------------------------

test.describe("Filter Pills", () => {
  test.beforeEach(async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();
  });

  test("displays the filter pill bar (5 base, up to 7 with Orphaned/Stale)", async ({
    dashboardPage,
  }) => {
    // e2e-pill-count-assertion-outdated: RunFilterBar now renders 7 pills —
    // All, Needs you, Waiting, Orphaned, Stale, Completed, Failed — but the
    // Orphaned and Stale pills are hidden when their count is 0. So the always-
    // present set is 5 and the maximum is 7.
    // Count the actual status pills by their testid prefix. getFilterPills()
    // matches every button inside filter-bar, which now also hosts the sort
    // toggle AND the two Board|List view-toggle segments (SPEC-vibekanban
    // §6.1), so a raw button count is no longer a meaningful pill count.
    const pills = dashboardPage.page.locator('[data-testid^="filter-pill-"]');
    const count = await pills.count();
    expect(count).toBeGreaterThanOrEqual(5);
    expect(count).toBeLessThanOrEqual(7);

    // The 5 always-visible pills must each be present, by testid.
    for (const value of ["all", "needsyou", "waiting", "completed", "failed"]) {
      await expect(dashboardPage.getFilterPill(value)).toBeVisible();
    }
  });

  test("All filter pill is active by default", async ({ dashboardPage }) => {
    const allPill = dashboardPage.getFilterPill("all");
    await expect(allPill).toBeVisible();
    // UX-R3 §14.2 (owner gate 2026-07-06, option a): the active pill is neutral
    // (foreground ink + subtle fill + 2px underline), not magenta.
    await expect(allPill).toHaveClass(/bg-foreground/);
  });

  test("filter pills display correct labels", async ({ dashboardPage }) => {
    // e2e-pill-labels-missing-new-pills: cover the triage pills (Needs you,
    // Orphaned, Stale) alongside the base set. Note the "waiting" pill is now
    // labelled "Waiting" (not "Running").
    await expect(dashboardPage.getFilterPill("all")).toContainText("All");
    await expect(dashboardPage.getFilterPill("needsyou")).toContainText("Needs you");
    await expect(dashboardPage.getFilterPill("waiting")).toContainText("Waiting");
    await expect(dashboardPage.getFilterPill("completed")).toContainText("Completed");
    await expect(dashboardPage.getFilterPill("failed")).toContainText("Failed");

    // Orphaned / Stale pills are only rendered when their count > 0, so assert
    // their labels conditionally (tolerating 0-count buckets in real data).
    const orphanedPill = dashboardPage.getFilterPill("orphaned");
    if (await orphanedPill.isVisible().catch(() => false)) {
      await expect(orphanedPill).toContainText("Orphaned");
    }
    const stalePill = dashboardPage.getFilterPill("stale");
    if (await stalePill.isVisible().catch(() => false)) {
      await expect(stalePill).toContainText("Stale");
    }
  });

  test("triage pills expose aria-pressed state", async ({ dashboardPage }) => {
    // e2e-pill-labels-missing-new-pills: the pills are toggle buttons; the
    // active one reports aria-pressed="true". "All" is active on load.
    await expect(dashboardPage.getFilterPill("all")).toHaveAttribute(
      "aria-pressed",
      "true"
    );
    await expect(dashboardPage.getFilterPill("needsyou")).toHaveAttribute(
      "aria-pressed",
      "false"
    );

    // Selecting the "Needs you" pill flips the aria-pressed state.
    await dashboardPage.clickFilterByValue("needsyou");
    await expect(dashboardPage.getFilterPill("needsyou")).toHaveAttribute(
      "aria-pressed",
      "true"
    );
    await expect(dashboardPage.getFilterPill("all")).toHaveAttribute(
      "aria-pressed",
      "false"
    );
  });

  test("filter pills show count badges when runs exist", async ({ dashboardPage }) => {
    // The "All" pill should show the total run count
    const allPill = dashboardPage.getFilterPill("all");
    await expect(allPill).toContainText(String(gridRunCount()));

    // Completed pill should show completed count
    if ((manifest.statusCounts.completed || 0) > 0) {
      const completedPill = dashboardPage.getFilterPill("completed");
      await expect(completedPill).toContainText(
        String(manifest.statusCounts.completed)
      );
    }

    // Failed pill should show failed count
    if ((manifest.statusCounts.failed || 0) > 0) {
      const failedPill = dashboardPage.getFilterPill("failed");
      await expect(failedPill).toContainText(String(manifest.statusCounts.failed));
    }
  });

  // e2e-filter-tests-stale-contradict-feature: page.tsx now renders the flat
  // <RunList> (not the project grid) for any non-"all" status filter. These
  // tests were rewritten to assert the flat run-list is shown and the project
  // grid is gone, instead of the removed "filtered project grid" behavior.

  test("clicking Waiting filter shows the flat run list, not project cards", async ({
    dashboardPage,
  }) => {
    await dashboardPage.clickFilterByValue("waiting");

    // The Waiting pill becomes the active (highlighted) pill.
    await expect(dashboardPage.getFilterPill("waiting")).toHaveClass(/bg-foreground/); // UX-R3 §14.2 (owner gate 2026-07-06, option a): active pill is neutral (foreground ink + fill + underline), not magenta

    // The project grid / cards are replaced by the flat list (or the shared
    // empty state when there are no waiting runs).
    await dashboardPage.waitForRunList();
    await expect(dashboardPage.projectGrid).toHaveCount(0);
    await expect(dashboardPage.getProjectCards()).toHaveCount(0);
  });

  test("clicking Completed filter shows the flat run list of completed runs", async ({
    dashboardPage,
  }) => {
    // Prefer a bucket known to be non-empty in real data so we can assert rows.
    if ((manifest.statusCounts.completed || 0) === 0) {
      test.skip();
      return;
    }

    await dashboardPage.clickFilterByValue("completed");
    await expect(dashboardPage.getFilterPill("completed")).toHaveClass(/bg-foreground/); // UX-R3 §14.2 (owner gate 2026-07-06, option a): active pill is neutral (foreground ink + fill + underline), not magenta

    // Flat list is visible with at least one run row, and no project cards.
    await dashboardPage.waitForRunList();
    await expect(dashboardPage.runList).toBeVisible();
    await expect(dashboardPage.runRows.first()).toBeVisible({ timeout: 15_000 });
    await expect(dashboardPage.getProjectCards()).toHaveCount(0);
  });

  test("clicking Failed filter shows the flat run list, not project cards", async ({
    dashboardPage,
  }) => {
    await dashboardPage.clickFilterByValue("failed");
    await expect(dashboardPage.getFilterPill("failed")).toHaveClass(/bg-foreground/); // UX-R3 §14.2 (owner gate 2026-07-06, option a): active pill is neutral (foreground ink + fill + underline), not magenta

    // Flat list (or empty state) replaces the grid; cards are gone. If there
    // are failed runs, at least one row is present.
    await dashboardPage.waitForRunList();
    await expect(dashboardPage.getProjectCards()).toHaveCount(0);
    if ((manifest.statusCounts.failed || 0) > 0) {
      await expect(dashboardPage.runList).toBeVisible();
      await expect(dashboardPage.runRows.first()).toBeVisible({ timeout: 15_000 });
    }
  });

  test("clicking All filter restores the project grid", async ({ dashboardPage }) => {
    // Apply a non-"all" filter → flat list, then All → grid restored.
    await dashboardPage.clickFilterByValue("failed");
    await dashboardPage.waitForRunList();
    await expect(dashboardPage.getProjectCards()).toHaveCount(0);

    await dashboardPage.clickFilterByValue("all");
    await expect(dashboardPage.getFilterPill("all")).toHaveClass(/bg-foreground/); // UX-R3 §14.2 (owner gate 2026-07-06, option a): active pill is neutral (foreground ink + fill + underline), not magenta

    // Grid comes back with every project card.
    await expect(dashboardPage.projectGrid).toBeVisible({ timeout: 15_000 });
    const allProjects = Object.keys(manifest.projectCounts);
    await expect(dashboardPage.getProjectCards()).toHaveCount(allProjects.length);
  });

  test("switching between grid and flat list toggles the two views", async ({
    dashboardPage,
  }) => {
    const totalProjects = Object.keys(manifest.projectCounts).length;

    // Initially the "all" grid shows every project card.
    await expect(dashboardPage.getProjectCards()).toHaveCount(totalProjects);
    await expect(dashboardPage.runList).toHaveCount(0);

    // Switch to a status filter → flat list, no grid.
    await dashboardPage.clickFilterByValue("failed");
    await dashboardPage.waitForRunList();
    await expect(dashboardPage.getProjectCards()).toHaveCount(0);

    // Switch back to All → grid restored, flat list gone.
    await dashboardPage.clickFilterByValue("all");
    await expect(dashboardPage.getProjectCards()).toHaveCount(totalProjects);
    await expect(dashboardPage.runList).toHaveCount(0);
  });
});

// ---------------------------------------------------------------------------
// Flat Run List (filter → list)  — e2e-no-filter-to-flatlist-test
// ---------------------------------------------------------------------------

test.describe("Flat Run List", () => {
  test.beforeEach(async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();
  });

  test("selecting a status filter replaces the project grid with the flat run list", async ({
    dashboardPage,
  }) => {
    // Headline UX: pick a non-empty bucket so we can assert real rows. Prefer
    // completed (usually populated); fall back to failed; otherwise skip.
    let filter: string | null = null;
    if ((manifest.statusCounts.completed || 0) > 0) filter = "completed";
    else if ((manifest.statusCounts.failed || 0) > 0) filter = "failed";
    if (!filter) {
      test.skip();
      return;
    }

    // Grid is present before filtering.
    await expect(dashboardPage.projectGrid).toBeVisible();

    await dashboardPage.clickFilterByValue(filter);
    await dashboardPage.waitForRunList();

    // Flat list and its rows are visible; the project grid and cards are gone.
    await expect(dashboardPage.runList).toBeVisible();
    await expect(dashboardPage.runRows.first()).toBeVisible({ timeout: 15_000 });
    await expect(dashboardPage.projectGrid).toHaveCount(0);
    await expect(dashboardPage.getProjectCards()).toHaveCount(0);

    // Each run row is a link to the run detail page.
    const href = await dashboardPage.runRows.first().getAttribute("href");
    expect(href).toMatch(/^\/runs\/[A-Z0-9]+$/);

    // Clicking "All" restores the project grid.
    await dashboardPage.clickFilterByValue("all");
    await expect(dashboardPage.projectGrid).toBeVisible({ timeout: 15_000 });
    await expect(dashboardPage.runList).toHaveCount(0);
    await expect(dashboardPage.getProjectCards().first()).toBeVisible();
  });

  test("clicking a run row navigates to the run detail page", async ({
    dashboardPage,
    page,
  }) => {
    if ((manifest.statusCounts.completed || 0) === 0) {
      test.skip();
      return;
    }

    await dashboardPage.clickFilterByValue("completed");
    await dashboardPage.waitForRunList();
    await expect(dashboardPage.runRows.first()).toBeVisible({ timeout: 15_000 });

    await dashboardPage.runRows.first().click();
    await page.waitForURL(/\/runs\/[A-Z0-9]+/, { timeout: 30_000 });
    expect(page.url()).toContain("/runs/");
  });
});

// ---------------------------------------------------------------------------
// Run Cards & Navigation
// ---------------------------------------------------------------------------

test.describe("Run Cards", () => {
  test.beforeEach(async ({ dashboardPage }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();
  });

  test("expanding a project card shows run cards with status badges", async ({
    dashboardPage,
    page,
  }) => {
    // Expand the first project card
    const firstCard = dashboardPage.getProjectCards().first();
    await firstCard.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    // Wait for run cards to load
    const runCards = dashboardPage.getRunCards();
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Each run card should contain a status badge text
    const count = await runCards.count();
    expect(count).toBeGreaterThan(0);

    for (let i = 0; i < Math.min(count, 5); i++) {
      const cardText = await runCards.nth(i).innerText();
      const hasStatus =
        cardText.includes("Completed") ||
        cardText.includes("Waiting") ||
        cardText.includes("Working") ||
        cardText.includes("Failed") ||
        cardText.includes("Running") ||
        cardText.includes("Pending");
      expect(hasStatus).toBe(true);
    }
  });

  test("run cards display task progress", async ({ dashboardPage }) => {
    // Expand the first project card
    const firstCard = dashboardPage.getProjectCards().first();
    await firstCard.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    const runCards = dashboardPage.getRunCards();
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Run cards should show task counts like "X/Y tasks"
    const firstRunText = await runCards.first().innerText();
    expect(firstRunText).toMatch(/\d+\/\d+ tasks/);
  });

  test("run cards display duration", async ({ dashboardPage }) => {
    // Expand the first project card
    const firstCard = dashboardPage.getProjectCards().first();
    await firstCard.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    const runCards = dashboardPage.getRunCards();
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Run cards should show duration (e.g. "2m 30s" or "< 1s")
    const firstRunText = await runCards.first().innerText();
    // Duration format: Xs, Xm, Xh, or "< 1s"
    expect(firstRunText).toMatch(/(\d+[smh]|< 1s)/);
  });

  test("clicking a run card navigates to /runs/[runId]", async ({
    dashboardPage,
    page,
  }) => {
    // Expand the first project card
    const firstCard = dashboardPage.getProjectCards().first();
    await firstCard.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    // Wait for run cards
    const runCards = dashboardPage.getRunCards();
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Get the href of the first run card
    const href = await runCards.first().getAttribute("href");
    expect(href).toMatch(/^\/runs\/[A-Z0-9]+$/);

    // Click the first run card
    await runCards.first().click();

    // Verify navigation to the run detail page
    await page.waitForURL(/\/runs\/[A-Z0-9]+/, { timeout: 30_000 });
    expect(page.url()).toContain("/runs/");
  });

  test("run card links have valid runId in href", async ({ dashboardPage }) => {
    // Expand the first project card
    const firstCard = dashboardPage.getProjectCards().first();
    await firstCard.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    const runCards = dashboardPage.getRunCards();
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    const count = await runCards.count();
    for (let i = 0; i < Math.min(count, 5); i++) {
      const href = await runCards.nth(i).getAttribute("href");
      expect(href).toBeTruthy();
      expect(href).toMatch(/^\/runs\/01[A-Z0-9]+$/);
    }
  });
});

// ---------------------------------------------------------------------------
// Pagination within Expanded Project Cards
// ---------------------------------------------------------------------------

test.describe("Pagination", () => {
  test("pagination controls appear for projects with more than 5 runs", async ({
    dashboardPage,
    page,
  }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Find a project with more than 5 runs
    const projectsWithManyRuns = Object.entries(manifest.projectCounts)
      .filter(([_, count]) => count > 5)
      .map(([name]) => name);

    if (projectsWithManyRuns.length === 0) {
      test.skip();
      return;
    }

    const projectName = projectsWithManyRuns[0];
    const card = dashboardPage.getProjectCard(projectName);
    await card.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    // Wait for run cards to load
    const runCards = page.locator(
      `[data-testid="project-card-${projectName}"] a[href^="/runs/"]`
    );
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Pagination controls should be visible (Previous/Next page buttons)
    const prevButton = page.getByRole("button", { name: "Previous page" });
    const nextButton = page.getByRole("button", { name: "Next page" });

    await expect(nextButton).toBeVisible({ timeout: 5_000 });

    // Previous button should be disabled on first page
    await expect(prevButton).toBeDisabled();
  });

  test("clicking next page loads more runs", async ({ dashboardPage, page }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Find a project with more than 5 runs
    const projectsWithManyRuns = Object.entries(manifest.projectCounts)
      .filter(([_, count]) => count > 5)
      .map(([name]) => name);

    if (projectsWithManyRuns.length === 0) {
      test.skip();
      return;
    }

    const projectName = projectsWithManyRuns[0];
    const card = dashboardPage.getProjectCard(projectName);
    await card.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    // Wait for runs to load
    const projectCard = page.getByTestId(`project-card-${projectName}`);
    const runCards = projectCard.locator('a[href^="/runs/"]');
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Should show up to 5 runs on first page
    const firstPageCount = await runCards.count();
    expect(firstPageCount).toBeLessThanOrEqual(5);

    // Click next page
    const nextButton = projectCard.getByRole("button", { name: "Next page" });
    await nextButton.click();

    // Wait for new runs to appear (the content will update)
    await page.waitForTimeout(1000);

    // The page indicator should now show "2"
    const pageIndicator = projectCard.locator(
      ".text-primary.bg-primary\\/10"
    );
    await expect(pageIndicator).toContainText("2");
  });
});

// ---------------------------------------------------------------------------
// Empty State (flat run-list, when a status filter yields no matching runs)
//   e2e-filter-tests-stale-contradict-feature: retargeted from the removed
//   filtered project-grid + expand-card model to the flat <RunList>, which
//   renders the shared <EmptyState> ("No runs found") for a 0-run bucket.
// ---------------------------------------------------------------------------

test.describe("Empty State", () => {
  test("flat list shows the shared empty state for a status bucket with zero runs", async ({
    dashboardPage,
  }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Pick a status filter whose bucket is empty in the fixtures so we can
    // observe the flat-list empty state. If every direct bucket is populated,
    // skip (nothing to assert without a zero-count bucket).
    const directStatuses: Array<{ value: string; count: number }> = [
      { value: "waiting", count: manifest.statusCounts.waiting || 0 },
      { value: "completed", count: manifest.statusCounts.completed || 0 },
      { value: "failed", count: manifest.statusCounts.failed || 0 },
    ];
    const emptyBucket = directStatuses.find((s) => s.count === 0);
    if (!emptyBucket) {
      test.skip();
      return;
    }

    await dashboardPage.clickFilterByValue(emptyBucket.value);
    await dashboardPage.waitForRunList();

    // The shared empty state text is shown, and there is no project grid/cards.
    await expect(dashboardPage.page.getByText("No runs found")).toBeVisible();
    await expect(dashboardPage.runRows).toHaveCount(0);
    await expect(dashboardPage.getProjectCards()).toHaveCount(0);
  });

  test("switching between status filters swaps the flat list contents", async ({
    dashboardPage,
  }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Apply the Failed filter → flat list (rows if any failed runs exist,
    // otherwise the shared empty state). Never the project grid.
    await dashboardPage.clickFilterByValue("failed");
    await dashboardPage.waitForRunList();
    await expect(dashboardPage.getProjectCards()).toHaveCount(0);
    if ((manifest.statusCounts.failed || 0) > 0) {
      await expect(dashboardPage.runList).toBeVisible();
      await expect(dashboardPage.runRows.first()).toBeVisible({ timeout: 15_000 });
    } else {
      await expect(dashboardPage.page.getByText("No runs found")).toBeVisible();
    }

    // Switch to the Completed filter — the flat list updates in place, still
    // no project grid/cards.
    await dashboardPage.clickFilterByValue("completed");
    await dashboardPage.waitForRunList();
    await expect(dashboardPage.getProjectCards()).toHaveCount(0);
    if ((manifest.statusCounts.completed || 0) > 0) {
      await expect(dashboardPage.runList).toBeVisible();
      await expect(dashboardPage.runRows.first()).toBeVisible({ timeout: 15_000 });
    } else {
      await expect(dashboardPage.page.getByText("No runs found")).toBeVisible();
    }
  });
});

// ---------------------------------------------------------------------------
// Theme Toggle
// ---------------------------------------------------------------------------

test.describe("Theme Toggle", () => {
  test("theme toggle button is accessible", async ({ dashboardPage, page }) => {
    await dashboardPage.goto();
    await expect(dashboardPage.heading).toBeVisible({ timeout: 30_000 });

    // The theme toggle button should have a title attribute
    const themeButton = page.locator("button[title*='Switch to']");
    await expect(themeButton).toBeVisible();

    const title = await themeButton.getAttribute("title");
    expect(title).toMatch(/Switch to (light|dark) theme/);
  });
});

// ---------------------------------------------------------------------------
// Settings Modal
// ---------------------------------------------------------------------------

test.describe("Settings Modal", () => {
  test("clicking settings button opens settings modal", async ({
    dashboardPage,
    page,
  }) => {
    await dashboardPage.goto();
    await expect(dashboardPage.heading).toBeVisible({ timeout: 30_000 });

    // Wait for the page to fully stabilize before clicking the settings button.
    // The dashboard may still be loading data which can cause SSE-related re-renders
    // that interfere with the click handler registration.
    await dashboardPage.waitForData();

    // Deterministic open (settings-flake class): re-clicks until the modal
    // mounts instead of one blind click + a long toBeVisible timeout — see
    // DashboardPage.openSettings for the root-cause note.
    await dashboardPage.openSettings();

    // Settings modal should become visible (Radix Dialog.Portal may take a moment)
    await expect(page.getByTestId("settings-modal")).toBeVisible();
  });
});

// ---------------------------------------------------------------------------
// Cross-Cutting Concerns
// ---------------------------------------------------------------------------

test.describe("Dashboard Accessibility", () => {
  test("page has a main heading", async ({ dashboardPage }) => {
    await dashboardPage.goto();
    const heading = dashboardPage.page.getByRole("heading", {
      name: "Babysitter Observer",
    });
    await expect(heading).toBeVisible({ timeout: 30_000 });
  });

  test("filter pills are keyboard accessible buttons", async ({
    dashboardPage,
  }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    const pills = dashboardPage.getFilterPills();
    const count = await pills.count();
    for (let i = 0; i < count; i++) {
      const tagName = await pills.nth(i).evaluate((el) => el.tagName);
      expect(tagName.toLowerCase()).toBe("button");
    }
  });

  test("pagination buttons have aria-labels", async ({
    dashboardPage,
    page,
  }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Find a project with enough runs for pagination
    const projectsWithManyRuns = Object.entries(manifest.projectCounts)
      .filter(([_, count]) => count > 5)
      .map(([name]) => name);

    if (projectsWithManyRuns.length === 0) {
      test.skip();
      return;
    }

    const projectName = projectsWithManyRuns[0];
    const card = dashboardPage.getProjectCard(projectName);
    await card.click();

    // Expand collapsed sub-sections (Failed Runs, Completed History) if present
    await dashboardPage.expandRunSubSections();

    // Wait for runs
    const runCards = card.locator('a[href^="/runs/"]');
    await expect(runCards.first()).toBeVisible({ timeout: 15_000 });

    // Check that pagination buttons have proper aria-labels
    const prevButton = page.getByRole("button", { name: "Previous page" });
    const nextButton = page.getByRole("button", { name: "Next page" });
    await expect(prevButton).toBeVisible();
    await expect(nextButton).toBeVisible();
  });
});

// ---------------------------------------------------------------------------
// Data Integrity
// ---------------------------------------------------------------------------

test.describe("Data Integrity", () => {
  test("project card run counts match manifest data", async ({
    dashboardPage,
  }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Verify each project card exists and shows the expected total run count
    for (const [projectName, runCount] of Object.entries(
      manifest.projectCounts
    )) {
      const card = dashboardPage.getProjectCard(projectName);
      await expect(card).toBeVisible();
      // The card should contain the total run count
      await expect(card).toContainText(String(runCount));
    }
  });

  test("KPI totals are consistent with project card data", async ({
    dashboardPage,
  }) => {
    await dashboardPage.goto();
    await dashboardPage.waitForData();

    // Total Runs KPI should equal the sum of all project run counts
    const totalTile = dashboardPage.getMetricTile("total-runs");
    await expect(totalTile).toContainText(String(gridRunCount()));

    // The project count should match the number of unique projects
    const projectCount = Object.keys(manifest.projectCounts).length;
    await expect(dashboardPage.projectCount).toContainText(
      `${projectCount} project`
    );
  });
});
